### ISSUE TITLE
Como Administrador Quiero definir la cantidad de revisiones que debe tener cada propuesta

### ISSUE THREAD

**Issue by bananee** [EIS-Tod/tod#19]
Como Administrador 
Quiero definir la cantidad de revisiones que debe tener cada propuesta

Feature: Set the amount of evaluations for a proposal

Background:
  Given an admin user

Scenario: admin user do not set an amount of evaluations for proposals
  When an admin user visits admin page
  Then  amount of evaluations required should display 3 as default

Scenario: admin user sets an amount of evaluations for proposals
  When an admin user visits admin page
  And    changes the amount of evaluations for a proposal to 4
  Then  a success message is displayed with quantity 4

**Comment by AlvarezAriel** [comment]
## Vistas:

![alt tag](https://lh4.googleusercontent.com/g7jXpVqHoBtHkYmKQTHvn5kKdxGyfOvecCu72AzfFp4RFsIIRzt-u8mjWJ9N6ZJ0ouDMs0gu=w1576-h694-rw)

![alt tag](https://lh5.googleusercontent.com/H3wDr8IMZcb99QMeCTF-FhAo9qBTZP8OsKFAVzbCWguE2kQ1qV7iS6jjGw0C58hgUv--_Cmj=w1576-h694-rw)
