### ISSUE TITLE
Como Administrador 
Quiero poder enviar un mail al autor de una propuestas informando el resultado, cuando esta alcance las tres revisiones

### ISSUE THREAD

**Issue by bananee** [EIS-Tod/tod#29]

**Comment by AlvarezAriel** [comment]
US29
Como Administrador 
Quiero poder enviar un mail al autor de una propuestas informAndo el resultado, cuAndo esta alcance las tres revisiones

“Recuerden que en la US 'Como administrador quiero que cuAndo una propuesta alcance las 3 revisiones, se envíe un mail con el resultado al autor', debería habilitar un botón en la propuesta, para que el admin confirme el envío del mail si está conforme con las evaluaciones, como lo charlamos en la review.”

Feature: Poder enviar resultados al autor de una propuesta con al menos tres revisiones

Background:
Given an admin user
And    a “A” proposal with three revisions
And    a “B” proposal with two revisions


Scenario:  the proposal does have three revisions and should show “notificar resultado” button
When an admin user visits proposal “A” details
And    the proposal does have three revisions
Then  should see the "notificar resultado" button
When clicks on  “notificar resultado" button
Then  it should display  “Mail enviado correctamente”
 
Scenario: the proposal does have two revisions but should not show “notificar resultado” button
When an admin user visits proposal ”B” details
And    the proposal does not have three revisions
Then  should not see the "Notificar Resultado" button

CONSULTA: Dado que solo los usuarios logueados con su cuenta de github tienen mail, cómo deberíamos manejar la notificación a los usuarios que no lo tengan? Los obligamos a que lo informen en la creación de la propuesta o ya no debería existir la posibilidad de crear una propuesta si no se loguean por github? 

El siguiente escenario tendrá validez según la respuesta a la consulta:

Scenario: the proposal does have three revisions but author does not have email
When an admin user visits the proposal details
And    the proposal does have three revisions
When clicks on  “notificar resultado" button
Then  it should display  “El usuario no tiene mail”

**Comment by javierperini** [comment]
Vista US

Boton de notificar resultado

https://drive.google.com/file/d/0B5U3l66_ujdoMUhuV0JBcWxCaWs/view?usp=sharing
