### ISSUE TITLE
Como Usuario Quiero poder loguearme a la aplicacion con la API de LinkedIn

### ISSUE THREAD

**Issue by bananee** [EIS-Tod/tod#42]
Como Usuario Quiero poder loguearme a la aplicación con la API de LinkedIn 
Feature: Login with Linkedin

  Background:
    Given a user with a valid linkedin user

  Scenario: Login with my LinkedIn account
    When  visits the login page
    And   selects login with linkedin
    Then  user should be logged in

**Comment by AlvarezAriel** [comment]
![Alt text](http://s22.postimg.org/y1w01goi9/Screenshot_from_2015_06_27_21_18_36.png)

![Alt text](http://s22.postimg.org/s288xt3pt/Screenshot_from_2015_06_27_21_19_11.png)
