### ISSUE TITLE
Como Administrador Quiero quiero poder eliminar los comentarios de las propuestas

### ISSUE THREAD

**Issue by bananee** [EIS-Tod/tod#43]
Como Administrador Quiero quiero poder eliminar los comentarios de las propuestas
Feature: admin user can delete comments

Background:
  Given an admin user
  And    a regular user
  And    a revisor user
  And    a proposal with “un comentario” comment
 
Scenario: admin user can delete the comment
  When admin user visits the proposals list
  And    enters the details of the proposal
  And    click on the delete button of comment “un comentario”
  Then  it should display “Comentario eliminado”
  And    comment “un comentario” should not appear

Scenario: regular user cannot delete the comment
  When regular user visits the proposals list
  And    enters the details of the proposal
  And    click on the delete button of comment “un comentario”
  Then  it should display “No tienes permisos para eliminar comentarios”

Scenario: revisor user cannot delete the comment
  When regular user visits the proposals list
  And    enters the details of the proposal
  And    click on the delete button of comment “un comentario”
  Then  it should display “No tienes permisos para eliminar comentarios”

**Comment by javierperini** [comment]
Vista US

boton borrar comentario
https://drive.google.com/file/d/0B5U3l66_ujdoYklYdER3Y3dJR28/view?usp=sharing

borre el comentario
https://drive.google.com/file/d/0B5U3l66_ujdoZ21IM1FodjdFbjg/view?usp=sharing

sin permisos para borrar
https://drive.google.com/file/d/0B5U3l66_ujdoRWY1LWFFcTZVQjA/view?usp=sharing
